print("-----------------------------")
print("    STUDENT ID               ")
print("-----------------------------")
student_name = input("Student name : ")
Student_ID= input("student ID : ")
Department =input("Department : ")
Year =input("year : ")
University =input("University: ")
Phone_number=int(input("Phone number : "))
print("-----------------------------")
