print("AREA OF RECTANGLE IS")
Length =int (input("Length: "))
Width =int (input("Width: "))
print (Length*Width)
print ("=================================")
print("perimeter OF RECTANGLE IS")
Length =int (input("Length: "))
Width =int (input("Width: "))
addition =int (Length+Width)
print (2*addition)