print("===============================")
print("       EMPLOYEE PAYSLIP        ")
print("===============================")
Employee=(input("Employee: "))
Basic_Salary=(input ("Basic_Salary: "))
Transport_Allowance=(input ("Transport Allowance:  "))
Food_Allowance=(input ("Food Allowance:  "))   
print("===============================")
Gross_Salary=float(Transport_Allowance)+float(Food_Allowance)+float(Basic_Salary)+float(Employee)
print("Gross Salary",Gross_Salary)
print("===============================")