print("====================================")
print("             BMI REPORT             ")
print("====================================")
Name = input("Enter your name: ")
weight = float(input("Enter your weight in kg: "))
height = float(input("Enter your height in meters: "))
bmi = weight / (height ** 2)
print("BMI:", bmi)