print("====================================")
print("        Exam Result Report          ")
print("====================================")
Student_name =input("Student name: ")
phyton= float(input("phayton: "))
oop =float(input("oop: "))
javascript = float(input("javascript: "))
print("====================================")
print("Total Marks:", phyton + oop + javascript)