print("====================================")
print("       AKIBA STUDENT PROFILE        ")
print("====================================")
Name = input("Enter student name: ")
age = int(input("Enter student age: "))
Student_ID = input("Enter student ID: ")
City = input("Enter student city: ")
University = input("Enter student university: ")
Department = input("Enter student department: ")
Email = input("Enter student email: ")
Phone_number = input("Enter student phone number: ")
Favorite_programming_language = input("Enter student's favorite programming language: ")
Favorite_programming_language = input("Favorite_programming_language: ") 
Programming_Goal = input("Enter student programming goal: ")
print("====================================")